name: Java CI with Gradle

on:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          cache: 'gradle'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
      
      - name: Translate secrets of base64 into json
        env:
          TEST: ${{ secrets.TEST }}
        run: |
          touch /tmp/test.yml | base64 --decode > /tmp/test.yml | cat /tmp/test.yml

      - name: Build with Gradle
        run: gradle build --info -Dspring.profiles.active="/tmp/test.yml" -Dspring.config.location="tmp/test.yml" -Dspring.config.name="test" -Dspring.config.import="/tmp/test.yml" 

      - name: BootRun with Gradle
        run: gradle bootRun --info -Dspring.profiles.active="/tmp/test.yml" -Dspring.config.location="tmp/test.yml" -Dspring.config.name="test" -Dspring.config.import="/tmp/test.yml"
