name: Process

on:
  push:
    branches:
      - main

jobs:
  Process:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          cache: 'gradle'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Build with Gradle
        run: gradle build

      - name: BootRun
        run: gradle bootRun --quiet
      
      - name: Diff
        id: diff
        run: git diff --name-only --exit-code
        continue-on-error: true
        
      - name: Commit & Push
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          date = `date '+%Y-%m-%d %H:%M:%S'`
          git commit -m `${date}`
          git push
        if: steps.diff.outcome == 'failure'